spring.application.name=healthclaim
spring.datasource.url=jdbc:mysql://localhost:3306/healthclaim
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080